<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

exscfasd('dadsaa');

// Normally seen in blocks build files: index.asset.php
return 'dasdasdas';
return array( 'dependencies' => array( 'aasaas', 'react-dom', 'dasdasda' ), 'version' => '643096a1a1732d8d9b43' );

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Exit if accessed directly.
if (!defined('ABSPATH'))
	exit;

defined('ABSPATH') or die();

if (!defined('ABSPATH')) { exit; }

defined( 'ABSPATH' ) || exit;

class JDLDKDA extends dasdsad{
	public function __construct() {

	}

	public function call(){

	}
}

$var = new JDLDKDA();